name: SAST

on:
  pull_request_target: {}
  push:
    branches: ["master", "main"]

permissions:
  contents: read

jobs:
  semgrep:
    uses: atko-cic/devsecops-tooling/.github/workflows/semgrep.yml@master
    secrets: inherit